# Generated by Django 5.1.4 on 2025-01-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_jobcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('jobTitle', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('jobtype', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='page_ptr',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='Company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='Email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='Message',
            new_name='user_message',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='Name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='Phone',
            new_name='user_phone',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Jobcard',
        ),
    ]
